<?php

// function salary_types_form_alter(&$form, &$form_state, $form_id) {
//   $curl = curl_init();

//   curl_setopt_array($curl, array(
//     CURLOPT_URL => 'http://dummy.restapiexample.com/api/v1/employees',
//     CURLOPT_RETURNTRANSFER => TRUE,
//     CURLOPT_ENCODING => '',
//     CURLOPT_MAXREDIRS => 10,
//     CURLOPT_TIMEOUT => 0,
//     CURLOPT_FOLLOWLOCATION => TRUE,
//     CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
//     CURLOPT_CUSTOMREQUEST => 'GET',
//   ));

//   $response = curl_exec($curl);
//   $error = curl_errno($curl);
//   $decoded = json_decode($response, TRUE);
//   $data = $decoded['data'];
//   watchdog(

//     'Salary types',
//     'error: <pre>%error<pre>',
//     [
//       '%error' => print_r($error, TRUE),
//     ],
//     WATCHDOG_DEBUG

//   );
//   curl_close($curl);
//   var_dump($data);
//   die();
// }
